export const ENV = {
  PORT: process.env.PORT,
  ADMIN_TOKEN: process.env.ADMIN_TOKEN,
  CORS_ORIGIN: process.env.CORS_ORIGIN,
  MONGO_URL: process.env.MONGO_URL,
  SOCKET_URL: process.env.SOCKET_URL,
  JWT_SECRET: process.env.JWT_SECRET,
  IMAGE_URL: process.env.IMAGE_URL || "http://localhost:4000",
  SMTP_HOST: process.env.SMTP_HOST || "",
  SMTP_PORT: process.env.SMTP_PORT || "587",
  SMTP_USER: process.env.SMTP_USER || "",
  SMTP_PASS: process.env.SMTP_PASS || "",
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID || process.env.VITE_GOOGLE_CLIENT_ID || "",
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET || "",
  GOOGLE_CALLBACK_URL: process.env.GOOGLE_CALLBACK_URL || "",
};
